language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install coverage
  - pip install python-coveralls
  - python setup.py install
script:
  - coverage run --source=sanic_oop setup.py test
after_success:
  - coveralls